### ISSUE TITLE
Visuelles Überlagern von Relationen zwischen den gleichen Knotenpaaren

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#143]
The edge "bb:ServerCluster meta:entityTypeComponent bb:Server" is incorrect.

**Details**
Hier überlagern sich zwei Bezeichnungen für die Relation und man kann es nicht mehr lesen. Siehe auch #59 .AW

**Comment by KonradHoeffner** [comment]
There are only 212 node pairs with overlapping edges now:

```
select count(*)
{
select distinct ?s ?o
from <http://www.snik.eu/ontology>
{
?s ?p ?o.
?s ?q ?o.
filter(?p!=?q).
filter(isIRI(?o)).
filter(?p!=meta:subTopClass&&(?q!=meta:subTopClass))
}
}
```
From 10228 node pairs with edges:

```
select count(*)
{
select distinct ?s ?o
from <http://www.snik.eu/ontology>
{
?s ?p ?o.
?s a owl:Class.
?o a owl:Class.
}
}
```

So only 2% of edges should have this problem now.

**Comment by KonradHoeffner** [comment]
text-margin-x shifts along the x axis of the canvas and is thus not suitable.

**Comment by KonradHoeffner** [comment]
Alle Paare von Knoten, bei denen sich Kanten in Hin- und Rückrichtung überlappen:

Um die Tabelle voll zu sehen, bitte im Firefox https://userstyles.org/styles/97661/wide-my-github aktivieren

```
select distinct ?s ?o (GROUP_CONCAT(DISTINCT ?p; SEPARATOR=", ") AS ?hin) (GROUP_CONCAT(DISTINCT ?q; SEPARATOR=", ") AS ?zurueck)
from <http://www.snik.eu/ontology>
{
?s ?p ?o.
?o ?q ?s.
filter(?s<?o).
?s a owl:Class.
?o a owl:Class.
filter(?p!=?q).
filter(isIRI(?o)).
filter(?p!=meta:subTopClass&&(?q!=meta:subTopClass))
} group by ?s ?o
```


s | o | hin | zurueck
-- | -- | -- | --
http://www.snik.eu/ontology/bb/InternalQualityManagement | http://www.snik.eu/ontology/bb/QualityManagement | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/functionComponent
http://www.snik.eu/ontology/ob/InformationManagement | http://www.snik.eu/ontology/ob/OperationalManagementOfInformationSystems | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/it4it/Policy | http://www.snik.eu/ontology/it4it/PolicyComponent | http://www.snik.eu/ontology/it4it/keyDataObject | http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses
http://www.snik.eu/ontology/he/ItStrategie | http://www.snik.eu/ontology/he/Unternehmensstrategie | http://www.snik.eu/ontology/meta/isAssociatedWith, http://www.snik.eu/ontology/meta/isBasedOn | http://www.snik.eu/ontology/meta/entityTypeComponent
http://www.snik.eu/ontology/it4it/ITInitiative | http://www.snik.eu/ontology/it4it/ProjectComponent | http://www.snik.eu/ontology/it4it/keyDataObject | http://www.snik.eu/ontology/meta/isAssociatedWith, http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses
http://www.snik.eu/ontology/it4it/EnterpriseArchitectureComponent | http://www.snik.eu/ontology/it4it/ServiceArchitecture | http://www.snik.eu/ontology/it4it/keyDataObject, http://www.snik.eu/ontology/meta/isAssociatedWith, http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses | http://www.snik.eu/ontology/it4it/keyDataObject, http://www.snik.eu/ontology/meta/isAssociatedWith
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/bb/RepresentativeOfHospitalDepartment | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/meta/isevolved
http://www.snik.eu/ontology/he/Architektur | http://www.snik.eu/ontology/he/Architekturprinzip | http://www.snik.eu/ontology/meta/isBasedOn | http://www.snik.eu/ontology/meta/isAssociatedWith
http://www.snik.eu/ontology/ob/Subsystem | http://www.snik.eu/ontology/ob/System | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/entityTypeComponent
http://www.snik.eu/ontology/ob/Product | http://www.snik.eu/ontology/ob/SoftwareProduct | http://www.w3.org/2004/02/skos/core#related | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/ProjectExecution | http://www.snik.eu/ontology/ob/ProjectExecution | http://www.w3.org/2004/02/skos/core#broadMatch | http://www.w3.org/2004/02/skos/core#closeMatch
http://www.snik.eu/ontology/bb/InformationProcessing | http://www.snik.eu/ontology/bb/NonComputerBasedInformationProcessing | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/Monitoring | http://www.snik.eu/ontology/bb/Management | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/functionComponent
http://www.snik.eu/ontology/ob/Sponsor | http://www.snik.eu/ontology/ob/ProjectPlan | http://www.snik.eu/ontology/ob/approves | http://www.snik.eu/ontology/meta/roleComponent
http://www.snik.eu/ontology/ciox/Finanzwesensystem | http://www.snik.eu/ontology/ciox/SAPFI | http://www.snik.eu/ontology/meta/isBasedOn | http://www.w3.org/1999/02/22-rdf-syntax-ns#type
http://www.snik.eu/ontology/bb/Vendor | http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/meta/isevolved | http://www.snik.eu/ontology/meta/roleComponent
http://www.snik.eu/ontology/bb/Planning | http://www.snik.eu/ontology/bb/Management | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/functionComponent
http://www.snik.eu/ontology/it4it/PortfolioBacklogItem | http://www.snik.eu/ontology/it4it/PortfolioDemandComponent | http://www.snik.eu/ontology/it4it/keyDataObject, http://www.snik.eu/ontology/meta/isAssociatedWith | http://www.snik.eu/ontology/meta/isAssociatedWith, http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses
http://www.snik.eu/ontology/it4it/EnterpriseArchitectureComponent | http://www.snik.eu/ontology/it4it/StrategyToPortfolio | http://www.snik.eu/ontology/it4it/keyFunctionalComponent, http://www.snik.eu/ontology/meta/isAssociatedWith | http://www.snik.eu/ontology/meta/entityTypeComponent
http://www.snik.eu/ontology/bb/PatientCare | http://www.snik.eu/ontology/bb/OrderEntry | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/ob/InformationManagement | http://www.snik.eu/ontology/ob/StrategicManagementOfInformationSystems | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/it4it/ProposalComponent | http://www.snik.eu/ontology/it4it/ScopeAgreement | http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses | http://www.snik.eu/ontology/it4it/keyDataObject
http://www.snik.eu/ontology/it4it/Requirement | http://www.snik.eu/ontology/it4it/RequirementComponent | http://www.snik.eu/ontology/it4it/keyDataObject | http://www.snik.eu/ontology/meta/isAssociatedWith, http://www.snik.eu/ontology/meta/updates, http://www.snik.eu/ontology/meta/uses
http://www.snik.eu/ontology/bb/ProjectManagementBoard | http://www.snik.eu/ontology/bb/ProjectManager | http://www.snik.eu/ontology/meta/roleComponent | http://www.snik.eu/ontology/meta/communicatesWith
http://www.snik.eu/ontology/bb/InformationManagement | http://www.snik.eu/ontology/bb/StrategicInformationManagement | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/PatientCare | http://www.snik.eu/ontology/bb/ExecutionOfDiagnosticTherapeuticAndNursingProcedures | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/ob/InformationManagement | http://www.snik.eu/ontology/ob/TacticalManagementOfInformationSystems | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/ComputerBasedInformationProcessing | http://www.snik.eu/ontology/bb/InformationProcessing | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/functionComponent
http://www.snik.eu/ontology/it4it/ConceptualService | http://www.snik.eu/ontology/it4it/Policy | http://www.snik.eu/ontology/it4it/entityRelationship | http://www.snik.eu/ontology/it4it/policyToConceptualService
http://www.snik.eu/ontology/bb/PatientCare | http://www.snik.eu/ontology/bb/PatientAdmission | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/InformationManagement | http://www.snik.eu/ontology/bb/OperationalInformationManagement | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/HealthCareNetwork | http://www.snik.eu/ontology/bb/HealthsuranceCompany | http://www.snik.eu/ontology/meta/entityTypeComponent | http://www.snik.eu/ontology/meta/communicatesWith
http://www.snik.eu/ontology/bb/PatientCare | http://www.snik.eu/ontology/bb/DecisionMakingPlanningAndOrganizationOfPatientTreatment | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/bb/Directing | http://www.snik.eu/ontology/bb/Management | http://www.w3.org/2000/01/rdf-schema#subClassOf | http://www.snik.eu/ontology/meta/functionComponent
http://www.snik.eu/ontology/bb/InformationManagement | http://www.snik.eu/ontology/bb/TacticalInformationManagement | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf
http://www.snik.eu/ontology/ob/Bid | http://www.snik.eu/ontology/ob/Vendor | http://www.snik.eu/ontology/meta/functionComponent | http://www.snik.eu/ontology/ob/approves
http://www.snik.eu/ontology/bb/PatientCare | http://www.snik.eu/ontology/bb/PatientDischargeAndTransferToOtherstitutions | http://www.snik.eu/ontology/meta/functionComponent | http://www.w3.org/2000/01/rdf-schema#subClassOf

**Comment by KonradHoeffner** [comment]
Moved to the "next" milestone as we are waiting for @FranziskaJahn to create a property hierarchy of the meta model.

**Comment by KonradHoeffner** [comment]
The property hierarchy does not reduce this further. However it doesn't seem to be worth the effort in relation to the small number of cases now so I move this to later.
