### ISSUE TITLE
Remove jQuery, if possible

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/graph#150]
Alternatively, make it faster to load. It takes around 5 seconds for the DNS sometimes.

**Comment by T-P-1** [comment]
i tried minified.js. https://github.com/timjansen/minified.js/
its smaller, easy to include, but has no support for panzoom which is only for jquery..
maybe to be investigated later.
nice comparison: https://nerdkrams.de/6-leichtgewichtige-jquery-alternativen-im-funktionsvergleich/

**Comment by KonradHoeffner** [comment]
Panzoom was deleted in 89d66fe3583caf0432f1a6a2e327dd7eab5de2b7 so remove jQuery now, if possible.
