### ISSUE TITLE
customize shapes for hito and other external endpoints

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/graph#355]
At the moment, SNIK Graph only provides different colors and shapes for subclasses of SNIK meta model classes.

Presenting HITO would look better if those classes had different shapes and colors as well.

Generalize the color and shape mechanism and use that for HITO.

**Comment by KonradHoeffner** [comment]
In progress in branch feature-dataset.

**Comment by Yagnap** [comment]
This is in progress in branch feature-dataset again, right now there are issues with the SPARQL queries for HITO and the color getting applied for SNIK (basically the only thing that works is the SNIK shapes). I will continue this in a week or so.

I also added the JSON file for a HITO initial view (Metamodel)
