### ISSUE TITLE
Zusammenhang von SIM, TIM und OIM

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#376]
Ich hätte gerne die Abbildung Fig 9.1 aus dem Blauen Buch mit SNIK-Graph dargestellt und möglicherweise als die graphische Darstellung, die beim Start statt der Wolke dargestellt wird. 
Damit möge sich mal eine SHK befassen.

![grafik](https://user-images.githubusercontent.com/22190396/132549881-20f2ab76-de31-49ad-b3ba-e8425e7bb8bf.png)

**Comment by KonradHoeffner** [comment]
Haben wir noch eine SHK/WHK dafür? @AlfredWinter: Wird das noch gewünscht?

**Comment by KonradHoeffner** [comment]
Ich habe zu dieser Issue einige Mails erhalten, anscheinend gab es hier ein Problem mit dem automatischen Übernehmen in diese Issue, daher hier manuell:

> Von @AlfredWinter: Ich hatte gerade etwas Zeit und da habe ich mich selber daran gemacht, die Abbildung 9.1 aus dem alten BB bzw. 4.3 aus dem neuen BB im SNIK/graph zu rekonstruieren. So 100%ig geht es nicht, aber vielleicht ist es doch ein gutes Einstiegsbild für SNIK/graph. Was meinen Sie?


![image](https://github.com/snikproject/graph/assets/839577/63057ba7-c848-4d2f-a599-c8120850e758)

[snik.json](https://github.com/snikproject/graph/files/13174446/snik.json)

Leider ist die Datei im Cytoscape-Format und kann nicht geladen werden.
@KonradHoeffner: Herausfinden, ob sich das manuell in das PartView-Format umwandeln lässt (wahrscheinlich nicht), ansonsten müsste das z.B. eine SHK rekonstruieren.

**Comment by KonradHoeffner** [comment]
@Yagnap hat es erfolgreich repariert!
[sim-tim-oim.zip](https://github.com/snikproject/graph/files/13841037/sim-tim-oim.zip)

Allerdings ist der View mit über 5 MB ziemlich groß, vielleicht lassen sich die Positionen der unsichtbaren Knoten entfernen?

**Comment by Yagnap** [comment]
Finalised in commit 83dcead.
