### ISSUE TITLE
Tight Layout

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#387]
Please type your issue here:
Tight layout geht nicht, wenn nach einer star-operation das Ergebnis im neuen Teilmodell erscheint. Erst wenn man mit der Maus einmal ins Fenster geklickt hat, dann funktioniert es. 

!!Please do not delete the following text, because its the log for developers!!

```

Register Context Menu.
multiplexing of 1 elements (direct=true)
Separate subontologies unchecked
Separate subontologies unchecked
Separate subontologies unchecked
layout finished in 42 ms
multiplexing of 1 elements (direct=true)
Separate subontologies unchecked
Separate subontologies unchecked
Separate subontologies unchecked
```

**Comment by KonradHoeffner** [comment]
Meinen Sie mit "geht nicht", dass es einfriert und das Browsertab dann abstürzt (das Problem hatte ich) oder passiert bei Ihnen einfach nichts?

**Comment by KonradHoeffner** [comment]
Mh es passiert leider immer noch.
Auf meinem Rechner mit 8 GB stürzt das Fenster einfach ab, auf dem hier mit 32 GB bleibt es stattdessen stecken bei 15.5 GB RAM Verbrauch und geht nicht weiter.

**Comment by KonradHoeffner** [comment]
Komischerweise passiert es nicht, wenn man einen der Knoten aus der Startansicht für den Stern nimmt und auch nicht bei "Recalculate Layout" obwohl sich "Tight Layout" nur durch unwesentlich andere Konfigurationsparameter unterscheided.

**Comment by KonradHoeffner** [comment]
Ahh, der Unterschied zwischen den beiden ist, dass bei "Recalculate Layout" der save Parameter auf true gesetzt ist und beim tight layout auf false.

**Comment by KonradHoeffner** [comment]
Lokal mit "npm run dev" tritt der Fehler alledings nicht auf.

**Comment by KonradHoeffner** [comment]
Können Sie mal die "offline website storage" des Browsers löschen? Danach geht es bei mir.
Also im Firefox: <kbd>STRG</kbd>+ <kbd>SHIFT</kbd>+ <kbd>ENTF</kbd> -> Time Range "Everything" und Data "Offline website data" auswählen.

**Comment by AlfredWinter** [comment]
Ich habe Ihnen in der nextcloud ein Programm freigegeben. Bitte starten Sie es. Dann drücken Sie in der dritten Reihe zuerst den dritten Button und nacheinander die restlichen Buttons der Reihe.

**Comment by AlfredWinter** [comment]
Allerdings geht das Tight Layout nicht, solange noch Knoten geheileitet sind.

**Comment by KonradHoeffner** [comment]
> Allerdings geht das Tight Layout nicht, solange noch Knoten geheileitet sind.

Leider kann ich das Problem nicht nachstellen, im Firefox Developer Edition 106 funktioniert es bei mir jetzt immer, unabhängig davon ob die Knoten ausgewählt sind oder nicht.
Können Sie noch mal schreiben, welche genaue Umgebung Sie haben? Also welches Betriebssystem, welchen Browser, Browserversion und SNIK Graph commit?
Und cache und offline website data sind komplett gelöscht?
Solche Fehler die nur unter bestimmten Umständen auftreten sind leider schwer aufzuspüren, wäre es als Workaround für sie erst einmal möglich, statt dem "tight layout" das "recalculate layout" zu benutzen? Die beiden benutzen den gleichen Euler-Layoutalgorithmus, tight layout hat nur leicht andere Parameter und zieht die Knoten etwas näher zusammen.

**Comment by KonradHoeffner** [comment]
> Ich habe Ihnen in der nextcloud ein Programm freigegeben. Bitte starten Sie es. Dann drücken Sie in der dritten Reihe zuerst den dritten Button und nacheinander die restlichen Buttons der Reihe.

exe-Dateien kann ich leider unter Linux nicht ausführen :-(

**Comment by AlfredWinter** [comment]
Dann schauen Sie mal, ob Sie irgendwo ein Windows finden.
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Samstag, 8. Oktober 2022 00:21
An: snikproject/graph ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/graph] Tight Layout (Issue #387)
 
Ich habe Ihnen in der nextcloud ein Programm freigegeben. Bitte starten Sie es. Dann drücken Sie in der dritten Reihe zuerst den dritten Button und nacheinander die restlichen Buttons der Reihe.
exe-Dateien kann ich leider unter Linux nicht ausführen :-(

**Comment by AlfredWinter** [comment]
Schauen Sie sich das am besten mal bei mir an. Sind Sie am Montag am IMISE? Dann kommen Sie doch mal bei mir vorbei. 
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Samstag, 8. Oktober 2022 00:20
An: snikproject/graph ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/graph] Tight Layout (Issue #387)
 
Allerdings geht das Tight Layout nicht, solange noch Knoten geheileitet sind.
Leider kann ich das Problem nicht nachstellen, im Firefox Developer Edition 106 funktioniert es bei mir jetzt immer, unabhängig davon ob die Knoten ausgewählt sind oder nicht.
Können Sie noch mal schreiben, welche genaue Umgebung Sie haben? Also welches Betriebssystem, welchen Browser, Browserversion und SNIK Graph commit?
Und cache und offline website data sind komplett gelöscht?
Solche Fehler die nur unter bestimmten Umständen auftreten sind leider schwer aufzuspüren, wäre es als Workaround für sie erst einmal möglich, statt dem "tight layout" das "recalculate layout" zu benutzen? Die beiden benutzen den gleichen Euler-Layoutalgorithmus, tight layout hat nur leicht andere Parameter und zieht die Knoten etwas näher zusammen.

**Comment by KonradHoeffner** [comment]
Ja ich bin am Montag vor Ort, dann komme ich bei Ihnen vorbei!

**Comment by KonradHoeffner** [comment]
OK es ist ein ganz anderes Problem, als es bei mir auftrat:

* es passiert gleichermaßen bei "tight layout" als auch bei "recalculate layout"
* es friert nicht ein sondern es passiert nur nichts
* bevor die Auswahl entfernt wird durchs Klicken ins Leere erscheint in der Konsole der Fehler "B.scratch is undefined" (oder B.Scratch groß?)

**Comment by KonradHoeffner** [comment]
Durch schnelles und häufiges Klicken auf den Layoutknopf konnte ich das Problem bei mir jetzt auch nachstellen, das log ist:

```
Uncaught (in promise) TypeError: can't access property "body", B.scratch(...) is undefined
    S http://127.0.0.1:4173/assets/main.d1357a8d.js:149
    value http://127.0.0.1:4173/assets/main.d1357a8d.js:149
    forEach http://127.0.0.1:4173/assets/main.d1357a8d.js:59
    value http://127.0.0.1:4173/assets/main.d1357a8d.js:149
    value http://127.0.0.1:4173/assets/main.d1357a8d.js:149
    Lt http://127.0.0.1:4173/assets/main.d1357a8d.js:149
    u http://127.0.0.1:4173/assets/main.d1357a8d.js:149
```

**Comment by KonradHoeffner** [comment]
Die source maps sind jetzt online und damit dürfte das Problem leichter einzugrenzen sein.
@AlfredWinter können Sie das Problem bitte noch einmal auslösen und die Fehlermeldungen aus der Konsole hier einfügen? (STRG+Shift+I im Firefox -> Console -> z.B. Copy all Messages).

**Comment by KonradHoeffner** [comment]
```
Initializing main.ts:216:9

layout finished in 9301 ms log.ts:59:7

Replaced layout cache. log.ts:59:7

You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine. cytoscape.cjs.js:873:12

graph-init finished in 9 ms log.ts:59:7

Create view Teilmodell 1 with 10501 hidden elements copied from Gesamtmodell. log.ts:59:7

Register Context Menu. log.ts:59:7

multiplexing of 1 elements (direct=true) log.ts:59:7

center

Object { 0: {…}, length: 1, _private: {…} }

graph.ts:197:10

star

Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }

graph.ts:232:10

Separate subontologies unchecked log.ts:59:7

layout finished in 120 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 104 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 110 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 134 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 109 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 129 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 128 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 126 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 137 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 124 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 150 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 128 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 123 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 146 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 131 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 133 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 130 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 118 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 132 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 121 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 129 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 126 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 124 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 121 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 122 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 116 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 123 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 113 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 107 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 104 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 107 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 107 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 109 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 116 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 102 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 271 ms log.ts:59:7

Separate subontologies unchecked log.ts:59:7

layout finished in 309 ms log.ts:59:7

filter node[source='meta'] triggered log.ts:59:7

filter node[source='meta'],node[source='bb'] triggered log.ts:59:7

filter node[source='meta'] triggered log.ts:59:7

filter node[source='meta'],node[source='ob'] triggered log.ts:59:7

filter node[source='meta'],node[source='ob'],node[source='ciox'] triggered log.ts:59:7

filter node[source='meta'],node[source='ob'],node[source='ciox'],node[source='he'] triggered log.ts:59:7

filter node[source='meta'],node[source='ob'],node[source='ciox'],node[source='he'],node[source='it'] triggered log.ts:59:7

filter node[source='meta'],node[source='ob'],node[source='ciox'],node[source='he'],node[source='it'],node[source='it4it'] triggered log.ts:59:7

You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine. cytoscape.cjs.js:873:12

graph-init finished in 11 ms log.ts:59:7

Create view Teilmodell 2 with 10501 hidden elements copied from Gesamtmodell. log.ts:59:7

Register Context Menu. log.ts:59:7

multiplexing of 1 elements (direct=true) log.ts:59:7

center

Object { 0: {…}, length: 1, _private: {…} }

graph.ts:197:10

star

Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }

graph.ts:232:10

Separate subontologies unchecked log.ts:59:7

Uncaught (in promise) TypeError: B.scratch(...) is undefined

    S cytoscape-euler.js:204

    value cytoscape-euler.js:274

    forEach cytoscape.cjs.js:11233

    value cytoscape-euler.js:272

    value cytoscape-euler.js:1126

    Lt layout.ts:159

    u viewLayout.ts:77

    wh viewLayout.ts:89

    emit goldenlayout.js:255

    _scheduleEventPropagationToLayoutManager goldenlayout.js:3662

    _propagateEvent goldenlayout.js:3645

    emit goldenlayout.js:265

    _propagateEvent goldenlayout.js:3643

    emit goldenlayout.js:265

    emitBubblingEvent goldenlayout.js:3580

    _$init goldenlayout.js:3568

    _$init goldenlayout.js:4441

    callDownwards goldenlayout.js:3134

    callDownwards goldenlayout.js:3137

    _create goldenlayout.js:1384

    init goldenlayout.js:706

    wh viewLayout.ts:92

    <anonymous> view.ts:12

cytoscape-euler.js:204:11
```

**Comment by KonradHoeffner** [comment]
Mit den Filtern habe ich es auch geschafft, den in der aktuellen Version auszulösen.

**Comment by KonradHoeffner** [comment]
Ich habe einen Fehlerkandidaten behoben, es wurden nämlich Kanten mit layouted und nicht nur Knoten, das könnte den Algorithmus durcheinandergebracht haben.
Jedenfalls kann ich auch diesen Fehler jetzt bei mir nicht mehr nachstellen.
@AlfredWinter können Sie mal gucken, ob nach Löschen des Caches (STRG+SHIFT+ENTF im Firefox) es jetzt auch bei Ihnen geht?

**Comment by AlfredWinter** [comment]
Geht jetzt bei mir J
 
 
[AW] 
Ich habe einen Fehlerkandidaten behoben, es wurden nämlich Kanten mit layouted und nicht nur Knoten, das könnte den Algorithmus durcheinandergebracht haben.
Jedenfalls kann ich auch diesen Fehler jetzt bei mir nicht mehr nachstellen.
@AlfredWinter können Sie mal gucken, ob nach Löschen des Caches (STRG+SHIFT+ENTF im Firefox) es jetzt auch bei Ihnen geht?

**Comment by KonradHoeffner** [comment]
Wunderbar, dann vielen Dank für den bug report und die Hilfe bei den Nachforschungen und ich schließe die Issue!

**Comment by KonradHoeffner** [comment]
P.S.: Falls dieser Fehler irgendwann doch mal wieder auftreten sollte, kann diese Issue wieder geöffnet werden, wenn wieder `B.scratch(...) is undefined` in der Konsole steht.
Für andere Layoutfehler ohne diese spezifische Fehlermeldung wäre eine neue Issue besser geeignet.
