### ISSUE TITLE
Local Installation Instructions

### ISSUE THREAD

**Issue by behollister** [snikproject/graph#393]
Browser: https://www.whatismybrowser.com/w/ERBFHNF

From Node instructions:

_git clone https://github.com/snikproject/snik-graph.git
npm install
cp js/config.dist.ts js/config.ts
npm run preview_

**Appears to missing a 'cd snik-graph' after 'git clone' line to indicate that 'npm install' must be run out of the repository directory.**

**Comment by KonradHoeffner** [comment]
Thank you for the correction! I added the `cd` statement to the documentation in commit b5a2ee34fd53fe514c08970420c4a9c13f696fc7.
