### ISSUE TITLE
Laden von Session/Teilmodell geht nicht!

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#403]
## Issue
Ich habe vergeblich versucht, den JSON File [https://my.hidrive.com/lnk/axPOh15C](url) wieder zu laden, den ich Ihnen geschickt hatte. Das funktioniert nicht :-(( 
## Version Info
SNIK Graph version 23.10-master
commit date 2023-10-02T18:33:55+02:00
update dependencies
master/1cb929a6347f0eceb811a767b53fd6a7bda4e279

## Log
```
graph-init finished in 12 ms
Load Graph from File: Visible fraction: NaN set star mode to false
Register Context Menu.
graph-init finished in 5 ms
Load Graph from File: Visible fraction: NaN set star mode to false
Register Context Menu.
graph-init finished in 8 ms
Load Graph from File: Visible fraction: NaN set star mode to false
Register Context Menu.
```

**Comment by KonradHoeffner** [comment]
Haben Sie vielleicht "Save the full SNIK Graph" ausgewählt? Dabei wird eine Cytoscape-Datei erzeugt, die von SNIK Graph nicht gelesen werden kann.
Das wird zwar im Tooltip erklärt aber ich sehe, dass das missverständlich benannt ist. Soll ich es in "Export to Cytoscape" umbenennen?
Wenn ich auf "Save Session" gehe erzeugt es eine snik-session.json und die lässt sich auch erfolgreich laden bei mir, können Sie das mal probieren?

Unabhängig davon funktioniert aber anscheinend "Save currently active view (partial graph)" momentan nicht, ich versuche das zu beheben.

**Comment by AlfredWinter** [comment]
Von: Konrad Höffner ***@***.***> 
Gesendet: Freitag, 13. Oktober 2023 16:13
An: snikproject/graph ***@***.***>
Cc: AlfredWinter ***@***.***>; Author ***@***.***>
Betreff: [Extern] Re: [snikproject/graph] Laden von Session/Teilmodell geht nicht! (Issue #403)
 
Haben Sie vielleicht "Save the full SNIK Graph" ausgewählt? 
[AW] Das weiß ich nicht mehr. Aber es ist ein .json File entstanden. 
Dabei wird eine Cytoscape-Datei erzeugt, die von SNIK Graph nicht gelesen werden kann.
Das wird zwar im Tooltip erklärt aber ich sehe, dass das missverständlich benannt ist. Soll ich es in "Export to Cytoscape" umbenennen?
[AW] Wäre vielleicht besser.

Wenn ich auf "Save Session" gehe erzeugt es eine snik-session.json und die lässt sich auch erfolgreich laden bei mir, können Sie das mal probieren?
[AW] Habe ich probiert. Dann wollte ich schon schreiben, dass es nicht geht, aber nach einer Weile kommt alles. Wir brauchen dann wohl eine Eieruhr. Offenbar hatte ich dann wohl tatsächlich "Save the full SNIK Graph" ausgewählt. Dann müssen wir das Bild noch einmal basteln …
Unabhängig davon funktioniert aber anscheinend "Save currently active view (partial graph)" momentan nicht, ich versuche das zu beheben.
[AW] Ja hatte ich auch gemerkt und ich meine, ich hätte das auch ins Github geschrieben.

**Comment by KonradHoeffner** [comment]
Die Probleme wurden behoben und erfolgreich getestet:

- [x] Speichern und Laden eines einzelnen Views
- [x] "Save full graph" umbenannt in "Export to Cytoscape"
- [x] "Save Session" und "Load Session" getestet

Wenn etwas davon wieder auftritt, bitte wieder öffnen.
