### ISSUE TITLE
Fehler snik/graph: Speichern von Teilmodell geht nicht

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#414]

**Comment by KonradHoeffner** [comment]
@AlfredWinter Bei mir geht es mit "Save currently active view (partial graph)"  und auch anschließendem Laden mit "Load Partial Graph into Session", könnten Sie es noch einmal probieren und das Log posten?
Bei mir sieht es so aus:

## Issue

## Version Info
SNIK Graph version 24.01
commit date 2024-01-31T09:59:11+01:00
chore: update deps
master/b67a14009b0342e2d6fc430c1261b536da7093a4

## Log
```
Menu added
search initialized
Main view unnamed loaded with 12283 elements.
Register Context Menu.
Set coloredEdges to true
graph-init finished in 4 ms
Create view Teilmodell 1 with 12283 hidden elements copied from Gesamtmodell.
Register Context Menu.
multiplexing of 17 elements (direct=true)
multiplexing of 1 elements (direct=true)
JSON File saved: snik-view.json
```

**Comment by AlfredWinter** [comment]
Ich habe länger nicht mit SNIK graph gearbeitet. Deshalb habe ich jetzt nach dem Feature zum Erzeugen eines neuen Teilmodells gesucht. Gefunden habe ich den winzigen button oben rechts mit dem Text "open new Tab". Dass ist zu unspezifisch. Dass muss heißen "open new partial graph" . Außerdem gehört ein solches Kommando auch in das Pulldown Menü "File". Am besten in die Nähe von "Load partial graph". (Warum steht da eigentlich "... into session"?)

**Comment by AlfredWinter** [comment]
Das Speichern und Laden geht jetzt bei mir auch mit "Save currently active view (partial graph)" und auch anschließendem Laden mit "Load Partial Graph into Session". Ich weiß leider nicht mehr was vor Wochen da nicht funktioniert hatte. 

Aber die Bezeichnungen sind verwirrend. Ich plädiere für folgende Features im File Menü:

- open new partial graph
- save partial graph (active tab)
- load partial graph

**Comment by KonradHoeffner** [comment]
> (Warum steht da eigentlich "... into session"?)

Das hatte Thomas Pause [in seiner Bachelorarbeit](https://www.snik.eu/public/bachelor-tp.pdf) systematisiert, davor war es noch verwirrender.

> Das eigene Datenformat .cys ermöglicht es, Sitzungen („sessions“) zu speichern und zu laden, was im Verlauf dieser Arbeit wichtig ist.

Und auch Seite 49 5.3 Abschnitt "Speichern und Laden von views und sessions":

> ...Dieses Verhalten impliziert auch eine neue Art des Ladens von Teilmodellen.
So können mittels Load Partial Graph into Session einzelne Views mit ihren Teilgraphen in eine gerade aktive Sitzung hineingeladen werden, ohne die Sitzung zu verlieren. Load Session hingegen überschreibt die aktuelle Arbeit und lädt die zuvor gespeicherte Sitzung komplett neu.

Also soll das verdeutlichen dass weder die anderen Views (Tabs) gelöscht werden noch der momentan geöffnete View überschrieben wird.

Davon abgegrenzt wird dann Funktionalität wie "Load Session", was alle momentan geöffneten Tabs schließt.

Aber wir können das gerne umbenennen, ich gerade "Tab" ist ja den meisten Nutzern durch Browser Tabs sehr geläufig, aber dann würde ich das gerne auch überall ersetzen, damit wir dann durchgehend die gleichen Begriffe haben.

**Comment by AlfredWinter** [comment]
(Warum steht da eigentlich "... into session"?)

Das hatte Thomas Pause in seiner Bachelorarbeit <https://www.snik.eu/public/bachelor-tp.pdf>  systematisiert, davor war es noch verwirrender.

Das eigene Datenformat .cys ermöglicht es, Sitzungen („sessions“) zu speichern und zu laden, was im Verlauf dieser Arbeit wichtig ist.

Und auch Seite 49 5.3 Abschnitt "Speichern und Laden von views und sessions":

...Dieses Verhalten impliziert auch eine neue Art des Ladens von Teilmodellen.
So können mittels Load Partial Graph into Session einzelne Views mit ihren Teilgraphen in eine gerade aktive Sitzung hineingeladen werden, ohne die Sitzung zu verlieren. Load Session hingegen überschreibt die aktuelle Arbeit und lädt die zuvor gespeicherte Sitzung komplett neu.

Also soll das verdeutlichen dass weder die anderen Views (Tabs) gelöscht werden noch der momentan geöffnete View überschrieben wird.

Davon abgegrenzt wird dann Funktionalität wie "Load Session", was alle momentan geöffneten Tabs schließt.

Aber wir können das gerne umbenennen, ich gerade "Tab" ist ja den meisten Nutzern durch Browser Tabs sehr geläufig, aber dann würde ich das gerne auch überall ersetzen, damit wir dann durchgehend die gleichen Begriffe haben.

[AW] „Tab“ ist ein technischer Begriff der GUI. Ein Nutzer will keinen Tab öffnen sondern einen partial graph. Zu den Begriffen Session, View und Partial Graph:

*	„View“ ist duch „partial graph“ zu ersetzen. 
*	Session ist mir auch zu technisch, aber es fällt mir nichts besseres ein. Also bleibt es so.

**Comment by KonradHoeffner** [comment]
Da das Speichern ja jetzt geht und die Umbenennung in eine andere Issue ausgelagert und behoben wurde, schließe ich diese Issue.
