### ISSUE TITLE
"submit Feedback about the Visualization" funktioniert nicht

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/graph#415]

**Comment by KonradHoeffner** [comment]
Bei mir geht es, können Sie es noch mal probieren? Vielleicht waren Sie nicht bei GitHub eingeloggt?

**Comment by KonradHoeffner** [comment]
Ich habe es heute nochmal getestet und es ging sowohl im Firefox (in GitHub eingeloggt, Issue hat sich geöffnet) und im Chrome (nicht eingeloggt, GitHub-Login-Fenster taucht auf). Daher schließe ich erstmal diese Issue, bitte wieder öffnen, falls das Problem wieder auftritt.

Ich füge auch Tooltips zu den Hilfeeinträgen hinzu, damit der GitHub-Login nicht zu Verwirrung führt.
