### ISSUE TITLE
Investigate instances

### ISSUE THREAD

**Issue by Yagnap** [snikproject/graph#420]
Check if the instances displayed when filtering out all non-instances are correctly classified as such

**Comment by KonradHoeffner** [comment]
This was a misunderstanding: we have a context menu option to show (via alert) instances of the selected class.
The filter on the other hand shows classes that have (shown with a star character "*" at the end of the label) respectively don't have (vast majority of classes) instances.
This was inconsistently and incorrectly described and documented, e196a26 fixes that and more.
