### ISSUE TITLE
"extended" has no indicator

### ISSUE THREAD

**Issue by Yagnap** [snikproject/graph#423]
### What happened?

When right-clicking any node in Chromium on Linux, the "extended" entry has no indicator that it has a submenu (appears as just any other button)

### Browsers

Chromium

### Operating systems

Linux

**Comment by Yagnap** [comment]
Seems like the image (which is missing in firefox as well) isn't discovered in the subfolder: node_modules/cytoscape-context-menus/assets/submenu-indicator-default.svg, but searched in assets/submenu-indicator-default.svg.
May be an upstream issue with the package.json, but the project hasn't been updated in 3 years (and pull requests not merged) and seems abandoned.
Working it looks like this: https://ivis-at-bilkent.github.io/cytoscape.js-context-menus/demo.html

**Comment by KonradHoeffner** [comment]
Thanks for the investigation! Can you point the path to the correct location?

**Comment by KonradHoeffner** [comment]
So what do we do differently that it works in the demo and not for us?

**Comment by Yagnap** [comment]
In the demo, all the files are positioned in the document root, while we use npm and have the library in a subfolder.

**Comment by KonradHoeffner** [comment]
Using npm seems like the default case so I think other people would also profit from you sharing your fix.
Could you create an issue at the library's GitHub repo and if it is possible in a reasonably short time consider making a pull request there?

**Comment by KonradHoeffner** [comment]
I'm reopening this issue because 2073d6bab669cc486d6d52b2f67b31d1112ce240 only solves the problem in the development environment where the node_modules folder exists but not in production.
