### ISSUE TITLE
add bb2

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/graph#440]
### What new feature do you want?

Add the new BB2 subontology.

**Comment by KonradHoeffner** [comment]
@Yagnap: Wie ist der Stand? Habe es gerade ausprobiert lokal, sehe aber noch nichts.

**Comment by Yagnap** [comment]
Momentan scheint bei der SPARQL-Query nichts zurückzukommen.
Selbst sowas wie die Query nach allen entity types (die laut RickView existieren) liefert 0 Ergebnisse (mit Graph IRI `http://www.snik.eu/ontology/bb2`):
```sparql
PREFIX meta: <http://www.snik.eu/ontology/meta/>
SELECT DISTINCT(?c) {
  ?c rdf:type meta:EntityType.
}
```

**Comment by KonradHoeffner** [comment]
Ich hatte mich mal beim Graph vertippt und das letztens von bb22 zu bb2 korrigiert.
Die SPARQL-Query funktioniert jetzt auch.

**Comment by Yagnap** [comment]
Sehr cool. Auf der bb2 branch sieht man jetzt auch was:

![snik](https://github.com/user-attachments/assets/9915c82e-2739-4136-850f-161edb641bca)

**Comment by Yagnap** [comment]
Super! Auf der bb2 branch sieht man jetzt auch was:

![snik](https://github.com/user-attachments/assets/fe823f42-507d-4e4c-a206-b939a8b2503f)

**Comment by Yagnap** [comment]
Fertig mit 76139e83dd23f9c7d876c7e0d5a0d54911d8256d.
