### ISSUE TITLE
Investigate more performant layout algorithms and/or graph libraries

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/graph#79]
https://github.com/anvaka/VivaGraphJS seems very performant, see http://www.yasiv.com/graphs#Bai/rw5151

**Comment by KonradHoeffner** [comment]
https://github.com/cytoscape/cytoscape.js-euler is at least fast enough to layout the whole graph, even though it takes more than 30 seconds on a fast PC. For now, solve this through layout caching and try to speed up incremental changes through fixed nodes.

See also https://github.com/cytoscape/cytoscape.js-euler/issues/4#issuecomment-321848878

**Comment by KonradHoeffner** [comment]
Create a demo with the SPARQL data using https://github.com/anvaka/VivaGraphJS.

**Comment by T-P-1** [comment]
an option here is to use a 3D Graph framework, like we tried here: 
https://github.com/T-P-1/JavaScript/tree/master/Graph
looks like: 
https://www.youtube.com/watch?v=AsY6TizcKzE

**Comment by KonradHoeffner** [comment]
The performance is still too low, especially with multiple tabs and on older machines, so it is time to look at the available options again:

-
